export type AgentMode = "research" | "workspace";
export type AgentThreadStatus = "idle" | "running" | "waiting" | "failed" | "interrupted";
export type AgentMessage = { id: string; role: "user" | "assistant"; text: string; createdAt: string };
export type AgentActivity = { id: string; type: string; title: string; status: string; detail?: string };
export type AgentApproval = { id: string; kind: "command" | "file" | "question"; title: string; detail: string;
  questions?: Array<{ id: string; header: string; question: string; options?: Array<{ label: string; description: string }> }> };
export type AgentThreadSummary = { id: string; title: string; createdAt: string; updatedAt: string; status: AgentThreadStatus;
  model: string; effort: string; mode: AgentMode; archived: boolean; inputTokens: number; outputTokens: number };
export type AgentThread = AgentThreadSummary & { messages: AgentMessage[]; activities: AgentActivity[]; approvals: AgentApproval[]; error: string | null };
export type AgentModel = { id: string; name: string; efforts: string[]; defaultEffort: string; isDefault: boolean };
export type AgentQuotaWindow = { name: string; usedPercent: number; windowMinutes: number; resetsAt: number };
export type AgentSettings = { dailyTurnLimit: number; dailyTokenBudget: number; maxTaskMinutes: number };
export type AgentStatus = { available: boolean; authenticated: boolean; account: { type: string; plan: string | null } | null;
  models: AgentModel[]; quota: { windows: AgentQuotaWindow[]; error: string | null; updatedAt: string | null };
  settings: AgentSettings; usage: { date: string; turns: number; inputTokens: number; outputTokens: number; activeTasks: number };
  login: { status: "idle" | "pending" | "complete" | "failed"; url?: string; code?: string; error?: string };
  error: string | null };
export type AgentCreateThread = { title?: string; model?: string; effort?: string; mode?: AgentMode };
export type AgentSendMessage = { text: string };
export type AgentApprovalDecision = { decision: "accept" | "decline"; answers?: Record<string, string[]> };
export type AgentThreadPatch = { title?: string; archived?: boolean };
