import { useState } from 'react';
import { ArrowUpRight, ChevronDown, RefreshCw, Search } from 'lucide-react';

export type Position = {symbol:string;local_symbol:string;type:string;quantity:number;average_cost:number|null;cost_basis:number|null;currency:string;con_id:number;multiplier:number|null;market_price:number|null;market_value:number|null;unrealized:number|null;unrealized_pct:number|null;realized:number|null;daily:number|null;expiry:string|null;strike:number|null;right:string|null;updated:number|null;can_chart:boolean};
export type Balances = {currency:string;account_type?:string|null;account_ready?:string|null;net_liquidation:number|null;cash:number|null;available:number|null;unrealized:number|null;realized?:number|null;daily?:number|null;buying_power?:number|null;settled_cash?:number|null;gross_position_value?:number|null;equity_with_loan?:number|null;initial_margin?:number|null;maintenance_margin?:number|null;excess_liquidity?:number|null;cushion?:number|null;sma?:number|null;accrued_interest?:number|null;accrued_dividend?:number|null;lookahead_available?:number|null;lookahead_excess?:number|null;lookahead_initial_margin?:number|null;lookahead_maintenance_margin?:number|null;lookahead_change?:number|null;day_trades_remaining?:number|null;leverage?:number|null;pnl_source?:string;portfolio_unrealized?:number|null;portfolio_realized?:number|null};
export type CurrencyRow = {currency:string;cash:number|null;total_cash:number|null;net_liquidation:number|null;exchange_rate:number|null;stock_value:number|null;option_value:number|null;unrealized:number|null;realized:number|null;accrued_interest:number|null};
export type AccountField = {tag:string;currency:string;value:string;source:string};
import type { Execution } from './executions';
export type { Execution } from './executions';
export const fmt=(n:number|null|undefined,digits=2)=>n==null?'—':n.toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const tone=(n:number|null|undefined)=>n==null||n===0?'':n<0?'negative':'positive';
const signed=(n:number|null|undefined)=>n==null?'—':(n>0?'+':'')+fmt(n);
const stamp=(n:number|string|null|undefined)=>n?new Date(typeof n==='number'?n*1000:n).toLocaleString('zh-CN',{timeZone:'America/New_York',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})+' ET':'等待券商更新';
const kind:Record<string,string>={STK:'股票 / ETF',OPT:'期权',FUT:'期货',FOP:'期货期权',CASH:'外汇',BOND:'债券',FUND:'基金',CRYPTO:'数字资产',WAR:'权证'};

export function PortfolioTable({positions,connected,onSelect}:{positions:Position[];connected:boolean;onSelect:(p:Position)=>void}) {
  return <><div className="portfolio-caption">市值与浮盈亏来自 IBKR 持仓估值，币种见各行；仅股票 / ETF 可打开 K 线。<span>均价按乘数换算 · 非基础币种持仓暂不显示当日盈亏</span></div><div className="table-wrap portfolio-table"><table><thead><tr><th>标的 / 合约</th><th>数量</th><th>均价 / 估值价</th><th>持仓市值</th><th>未实现盈亏</th><th>当日盈亏</th><th>已实现盈亏</th><th>币种 / 更新</th><th/></tr></thead><tbody>{positions.length?positions.map(p=><tr key={p.con_id}><td><b>{p.symbol}</b><small>{kind[p.type]||p.type}{p.type!=='STK'?' · '+p.local_symbol:''}</small>{p.multiplier!=null&&p.multiplier!==1&&<small>合约乘数 ×{fmt(p.multiplier,0)}</small>}</td><td className="numeric">{p.quantity==null?'—':fmt(p.quantity,Number.isInteger(p.quantity)?0:4)}</td><td className="numeric">{fmt(p.average_cost)}<small>{fmt(p.market_price)}</small></td><td className="numeric">{fmt(p.market_value)}</td><td className={'numeric '+tone(p.unrealized)}>{signed(p.unrealized)}<small>{p.unrealized_pct==null?'—':signed(p.unrealized_pct)+'%'}</small></td><td className={'numeric '+tone(p.daily)}>{signed(p.daily)}</td><td className={'numeric '+tone(p.realized)}>{signed(p.realized)}</td><td>{p.currency}<small>{stamp(p.updated)}</small></td><td>{p.can_chart?<button className="text-button" onClick={()=>onSelect(p)}>查看 K 线<ArrowUpRight size={12}/></button>:<span className="muted-cell">只读持仓</span>}</td></tr>):<tr><td colSpan={9}><div className="empty-table"><span>—</span>{connected?'暂无持仓':'连接账户后显示券商持仓估值'}</div></td></tr>}</tbody></table></div></>;
}

export function AccountOverview({balances:b,positions,currencies,fields,connected,updated,pnlUpdated,pnlError,onSelect}:{balances:Balances;positions:Position[];currencies:CurrencyRow[];fields:AccountField[];connected:boolean;updated:number|null;pnlUpdated:number|null;pnlError:string|null;onSelect:(p:Position)=>void}) {
  const [expanded,setExpanded]=useState(false),[query,setQuery]=useState('');
  const metrics:[string,number|null|undefined,string][]=[['购买力',b.buying_power,'Buying power'],['可用资金',b.available,'Available funds'],['超额流动性',b.excess_liquidity,'Excess liquidity'],['初始保证金',b.initial_margin,'Initial margin'],['维持保证金',b.maintenance_margin,'Maintenance margin'],['含贷款权益',b.equity_with_loan,'Equity with loan'],['持仓总值',b.gross_position_value,'Gross position value'],['已结算现金',b.settled_cash,'Settled cash'],['应计利息',b.accrued_interest,'Accrued interest'],['应计股息',b.accrued_dividend,'Accrued dividends'],['SMA',b.sma,'Special memorandum account']];
  const filtered=fields.filter(f=>[f.tag,f.currency,f.source].join(' ').toLowerCase().includes(query.toLowerCase()));
  return <div className="account-overview">
    <section className="account-pnl-grid" aria-label="账户盈亏"><div><span className="eyebrow">DAILY P&L</span><h2>当日盈亏</h2><strong className={tone(b.daily)}>{signed(b.daily)}</strong><small>{b.currency} · IBKR 盈亏流</small></div><div><span className="eyebrow">UNREALIZED P&L</span><h2>未实现盈亏</h2><strong className={tone(b.unrealized)}>{signed(b.unrealized)}</strong><small>{b.currency} · {b.pnl_source==='account-ledger'?'账户账本':'盈亏流'}</small></div><div><span className="eyebrow">REALIZED P&L</span><h2>已实现盈亏</h2><strong className={tone(b.realized)}>{signed(b.realized)}</strong><small>{b.currency} · 依 IBKR 当前统计口径</small></div><div className="account-pnl-note"><b>{b.account_type||'账户状态待同步'}</b><p>当日盈亏与持仓累计浮盈亏不同。已实现盈亏不是开户以来总收益，重置时间按 IBKR 设置。</p><small>盈亏更新 {stamp(pnlUpdated)}</small>{pnlError&&<p className="negative">{pnlError}</p>}</div></section>
    <section className="account-section"><div className="section-heading"><div><span className="eyebrow">CAPITAL & MARGIN</span><h2>资金与保证金</h2></div><span>{b.currency} · {stamp(updated)}</span></div><div className="account-metrics">{metrics.map(([label,value,en])=><div key={label}><span>{label}</span><strong>{fmt(value)}</strong><small>{en}</small></div>)}<div><span>风险缓冲 / 杠杆</span><strong>{b.cushion==null?'—':fmt(b.cushion*100)+'%'} <em>/ {b.leverage==null?'—':fmt(b.leverage)+'×'}</em></strong><small>Cushion / leverage</small></div></div><div className="account-lookahead"><span>下一时段预估</span><div>可用资金 <b>{fmt(b.lookahead_available)}</b></div><div>超额流动性 <b>{fmt(b.lookahead_excess)}</b></div><div>初始 / 维持保证金 <b>{fmt(b.lookahead_initial_margin)} / {fmt(b.lookahead_maintenance_margin)}</b></div><div>剩余日内次数 <b>{b.day_trades_remaining==null?'—':b.day_trades_remaining<0?'不适用 / 未限制':fmt(b.day_trades_remaining,0)}</b></div></div></section>
    <section className="account-section"><div className="section-heading"><div><span className="eyebrow">CURRENCY LEDGER</span><h2>多币种资产</h2></div><span>每行使用对应币种 · 汇率为折算至 {b.currency}</span></div><div className="table-wrap"><table><thead><tr><th>币种</th><th>现金余额</th><th>净清算价值</th><th>股票市值</th><th>期权市值</th><th>未实现盈亏</th><th>已实现盈亏</th><th>汇率</th></tr></thead><tbody>{currencies.length?currencies.map(c=><tr key={c.currency}><td><b>{c.currency}</b></td><td className="numeric">{fmt(c.cash)}</td><td className="numeric">{fmt(c.net_liquidation)}</td><td className="numeric">{fmt(c.stock_value)}</td><td className="numeric">{fmt(c.option_value)}</td><td className={'numeric '+tone(c.unrealized)}>{signed(c.unrealized)}</td><td className={'numeric '+tone(c.realized)}>{signed(c.realized)}</td><td className="numeric">{fmt(c.exchange_rate,6)}</td></tr>):<tr><td colSpan={8} className="account-empty">尚未收到币种账本。</td></tr>}</tbody></table></div></section>
    <section className="account-section"><div className="section-heading"><div><span className="eyebrow">COMPLETE PORTFOLIO</span><h2>全部持仓 <small>{positions.length}</small></h2></div><span>股票、期权及其他已持有合约</span></div><PortfolioTable positions={positions} connected={connected} onSelect={onSelect}/></section>
    <section className="account-section account-disclosure"><button className="account-disclosure-button" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}><span>更多 IBKR 返回字段 <small>{fields.length} 项</small></span><ChevronDown size={16} style={{transform:expanded?'rotate(180deg)':undefined}}/></button>{expanded&&<><div className="account-search"><Search size={14}/><input aria-label="搜索账户字段" placeholder="搜索字段、币种或数据来源" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-wrap account-raw"><table><thead><tr><th>IBKR 字段</th><th>值</th><th>币种</th><th>来源</th></tr></thead><tbody>{filtered.map(f=><tr key={f.tag+':'+f.currency}><td className="numeric">{f.tag}</td><td className="numeric">{f.value}</td><td>{f.currency||'不适用'}</td><td>{f.source}</td></tr>)}</tbody></table></div></>}<p>账户汇总和分币种账本分别展示，BASE 汇总不与各币种重复相加。横线表示尚未收到有效值；持仓估值不等于可成交的实时报价。不同 IBKR 数据流的更新时间和盈亏重置口径可能不同。</p></section>
  </div>;
}

export function BrokerExecutions({rows,updated,connected,onRefresh}:{rows:Execution[];updated:number|null;connected:boolean;onRefresh:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function refresh(){setBusy(true);setError('');try{await onRefresh();}catch(e){setError(e instanceof Error?e.message:'成交同步失败。');}finally{setBusy(false);}}
  return <section className="account-section broker-executions"><div className="section-heading"><div><span className="eyebrow">BROKER EXECUTIONS</span><h2>券商成交 <small>{rows.length}</small></h2></div><button className="history-more" disabled={!connected||busy} onClick={()=>void refresh()}><RefreshCw size={13} className={busy?'spin':''}/>{busy?'同步中':'同步成交'}</button></div><p className="portfolio-caption">显示已归档的最近 200 笔成交；K 线按标的加载全部归档记录。通过上方 Flex / 报表入口补齐旧交易。<span>{stamp(updated)}</span></p>{error&&<p className="inline-warning">{error}</p>}<div className="table-wrap"><table><thead><tr><th>标的 / 合约</th><th>方向</th><th>数量</th><th>成交价</th><th>交易所</th><th>佣金</th><th>时间（美东）</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.symbol}</b><small>{r.local_symbol}</small></td><td>{r.side==='BOT'?'买入':r.side==='SLD'?'卖出':r.side}</td><td>{fmt(r.quantity,4)}</td><td>{fmt(r.price,4)} <small>{r.currency}</small></td><td>{r.exchange}</td><td>{fmt(r.commission)} <small>{r.commission_currency}</small></td><td>{stamp(r.time)}</td></tr>):<tr><td colSpan={7} className="account-empty">{connected?'本次连接尚未收到可见成交，不代表账户没有历史交易。':'连接 IB Gateway 后同步可见成交。'}</td></tr>}</tbody></table></div></section>;
}
